=== theflashbum/FlashArtOfWarBlog/wp-content/plugins/social-bookmarks/social_bookmarks.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="social_sites">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="site">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="url" type="xs:string" />
              <xs:element name="img" type="xs:string" />
              <xs:element name="key" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== theflashbum/FlashArtOfWarBlog/wp-content/wp-content/plugins/social-bookmarks/sites_EN.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 
	Social Bookmarks
	
	English Language Pack
	version 4.2
	Copyright(c) Apostolos Dountsis
	http://www.dountsis.com
-->
<social_sites xsi:noNamespaceSchemaLocation="social_bookmarks.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <site>
    <name>BlinkList</name>
    <url>http://blinklist.com/index.php?Action=Blink/addblink.php&amp;Name={title}&amp;Description={title}&amp;Url={link}</url>
    <img>blinklist.png</img>
    <key>blinklist_en</key>
  </site>
  <site>
    <name>Bloglines</name>
    <url>http://www.bloglines.com/sub/{link}</url>
    <img>bloglines.png</img>
    <key>bloglines_en</key>
  </site>
  <site>
    <name>Blogmarks</name>
    <url>http://blogmarks.net/my/new.php?mini=1&amp;simple=1&amp;url={link}&amp;title={title}</url>
    <img>bmarks.png</img>
    <key>blogmarks_en</key>
  </site>
  <site>
    <name>Buzz</name>
    <url>http://buzz.yahoo.com/submit?submitUrl={link}&amp;submitHeadline={title}&amp;submitSummary=</url>
    <img>buzz.png</img>
    <key>buzz_en</key>
  </site>   
  <site>
    <name>Connotea</name>
    <url>http://www.connotea.org/addpopup?continue=confirm&amp;uri={link}&amp;title={title}</url>
    <img>connotea.png</img>
    <key>connotea_en</key>
  </site>
  <site>
    <name>Del.icio.us</name>
    <url>http://del.icio.us/post?url={link}&amp;title={title}</url>
    <img>delicious.png</img>
    <key>delicious_en</key>
  </site>
  <site>
    <name>Diigo</name>
    <url>http://www.diigo.com/post?url={link}&amp;title={title}</url>
    <img>diigo.png</img>
    <key>diigo_en</key>
  </site>
  <site>
    <name>digg</name>
    <url>http://digg.com/submit?phase=2&amp;url={link}&amp;title={title}</url>
    <img>digg.png</img>
    <key>digg_en</key>
  </site>
  <site>
    <name>DotNetKicks</name>
    <url>http://www.dotnetkicks.com/kick/?url={link}&amp;title={title}</url>
    <img>dotnetkicks.png</img>
    <key>dotnetkicks_en</key>
  </site>
  <site>
    <name>DZone</name>
    <url>http://www.dzone.com/links/add.html?description={title}&amp;url={link}&amp;title={title}</url>
    <img>dzone.png</img>
    <key>dzone_en</key>
  </site>
  <site>
    <name>Facebook</name>
    <url>http://www.facebook.com/sharer.php?u={link}</url>
    <img>facebook.png</img>
    <key>facebook_en</key>
  </site>
  <site>
    <name>Fark</name>
    <url>http://cgi.fark.com/cgi/fark/farkit.pl?u={link}&amp;h={title}</url>
    <img>fark.png</img>
    <key>fark_en</key>
  </site>
  <site>
    <name>Faves</name>
    <url>http://faves.com/Authoring.aspx?u={link}&amp;t={title}</url>
    <img>bluedot.png</img>
    <key>bluedot_en</key>
  </site>
  <site>
    <name>Fleck</name>
    <url>http://fleck.com/litebookmarklet.php?url={link}&amp;title={title}</url>
    <img>fleck.png</img>
    <key>fleck_en</key>
  </site>
  <site>
    <name>FriendSite</name>
    <url>http://FriendSite.com/users/bookmarks/?u={link}&amp;t={title}</url>
    <img>friendsite.png</img>
    <key>friendsite_en</key>
  </site>
  <site>
    <name>Google Bookmarks</name>
    <url>http://www.google.com/bookmarks/mark?op=edit&amp;output=popup&amp;bkmk={link}&amp;title={title}</url>
    <img>google.png</img>
    <key>google_en</key>
  </site>
  <site>
    <name>Kaboodle</name>
    <url>http://www.kaboodle.com/za/selectpage?p_pop=false&amp;pa=url&amp;u={link}</url>
    <img>kaboodle.png</img>
    <key>kaboodle_en</key>
  </site>
  <site>
     <name>Maple</name>
     <url>http://www.maple.nu/cgi-bin/search6/usa/ss_submit.cgi?fct=100&amp;url={link}&amp;title={title}"</url>
     <img>maple.png</img>
     <key>maple_en</key>
  </site>
  <site>
    <name>Mister Wong</name>
    <url>http://www.mister-wong.com/index.php?action=addurl&amp;bm_url={link}&amp;bm_description={title}</url>
    <img>misterwong.png</img>
    <key>misterwong_en</key>
  </site>
  <site>
    <name>Netscape</name>
    <url>http://www.netscape.com/submit/?U={link}&amp;T={title}</url>
    <img>netscape.png</img>
    <key>netscape_en</key>
  </site>
  <site>
    <name>Netvouz</name>
    <url>http://netvouz.com/action/submitBookmark?url={link}&amp;title={title}&amp;popup=no</url>
    <img>netvouz.png</img>
    <key>netvouz_en</key>
  </site>
  <site>
    <name>Newsvine</name>
    <url>http://www.newsvine.com/_wine/save?u={link}&amp;h={title}</url>
    <img>newsvine.png</img>
    <key>newsvine_en</key>
  </site>
  <site>
    <name>PlugIM</name>
    <url>http://www.plugim.com/submit?url={link}&amp;title={title}</url>
    <img>plugim.png</img>
    <key>plugim_en</key>
  </site>
  <site>
    <name>reddit</name>
    <url>http://reddit.com/submit?url={link}&amp;title={title}</url>
    <img>reddit.png</img>
    <key>reddit_en</key>
  </site>
  <site>
    <name>Simpy</name>
    <url>http://www.simpy.com/simpy/LinkAdd.do?href={link}&amp;title={title}</url>
    <img>simpy.png</img>
    <key>simpy_en</key>
  </site>
  <site>
    <name>Kirtsy</name>
    <url>http://www.kirtsy.com//submit.php?url={link}</url>
    <img>skirt.png</img>
    <key>skirt_en</key>
  </site>
  <site>
    <name>Slashdot</name>
    <url>http://slashdot.org/bookmark.pl?url={link}&amp;title={title}</url>
    <img>slashdot.png</img>
    <key>slashdot_en</key>
  </site>
  <site>
    <name>Stumble Upon</name>
    <url>http://www.stumbleupon.com/submit.php?url={link}&amp;title={title}</url>
    <img>stumbleupon.png</img>
    <key>stumbleupon_en</key>
  </site>
  <site>
    <name>Shoutwire</name>
    <url>http://www.shoutwire.com/?p=submit&amp;link={link}</url>
    <img>shoutwire.png</img>
    <key>shoutwire_en</key>
  </site>
  <site>
    <name>Squidoo</name>
    <url>http://www.squidoo.com/lensmaster/bookmark?{link}</url>
    <img>squidoo.png</img>
    <key>squidoo_en</key>
  </site>
  <site>
    <name>SphereIt</name>
    <url>http://www.sphere.com/sphereit/{link}</url>
    <img>sphereit.png</img>
    <key>sphereit_en</key>
  </site>
  <site>
    <name>Spurl</name>
    <url>http://www.spurl.net/spurl.php?url={link}&amp;title={title}</url>
    <img>spurl.png</img>
    <key>spurl_en</key>
  </site>
  <site>
    <name>Technorati</name>
    <url>http://www.technorati.com/faves?add={link}</url>
    <img>technorati.png</img>
    <key>technorati_en</key>
  </site>
  <site>
    <name>ThisNext</name>
    <url>http://www.thisnext.com/pick/new/submit/sociable/?url={link}&amp;name={title}</url>
    <img>thisnext.png</img>
    <key>thisnext_en</key>
  </site>
  <site>
    <name>Tip'd</name>
    <url>http://tipd.com/submit.php?url={link}</url>
    <img>tipd.png</img>
    <key>tipd_en</key>
  </site>
  <site>
    <name>Twitter</name>
    <url>http://twitter.com/home/?status=Check+out+{title}+@+{link}</url>
    <img>twitter.png</img>
    <key>twitter_en</key>
  </site>
  <site>
    <name>Webride</name>
    <url>http://webride.org/discuss/split.php?uri={link}&amp;title={title}</url>
    <img>webride.png</img>
    <key>webride_en</key>
  </site>
  <site>
    <name>Wists</name>
    <url>http://www.wists.com/t.php?c=null&amp;r={link}&amp;u={link}&amp;title={text}</url>
    <img>wists.png</img>
    <key>wists_en</key>
  </site>
  <site>
    <name>Yahoo My Web</name>
    <url>http://myweb2.search.yahoo.com/myresults/bookmarklet?u={link}&amp;t={title}</url>
    <img>yahoo.png</img>
    <key>yahoo_en</key>
  </site>
</social_sites>
